disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Experimento Rojo"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"

["params.author"]
name = "Elizabeth"
headline = "Hago cosas."
bio = "Epa"
